# application-prod.yml
spring:
  data:
    redis:
      host: 172.17.0.1
      port: 6379

#gemini:
#  api:
#    api-key: ${GEMINI_API_KEY}
#
#claude:
#  api:
#    api-key: ${CLAUDE_API_KEY}

clova:
  ocr:
    api-url: ${CLOVA_OCR_API_URL}
    secret-key: ${CLOVA_OCR_SECRET_KEY}

public-api:
  external:
    seoul-real-trade-key: ${EXTERNAL_SEOUL_REAL_TRADE_KEY}
    molit-building-key: ${EXTERNAL_MOLIT_BUILDING_KEY}
    seoul-rent-key: ${EXTERNAL_SEOUL_RENT_KEY}
    mois-address-key: ${EXTERNAL_MOIS_ADDRESS_KEY}
